/* ==========================================================================
   data.js — TODO el contenido del portafolio vive aquí.
   Edita este archivo para cambiar textos, experiencias, enlaces o archivos
   que aparecen en el IDE. No hace falta tocar nada más.
   ========================================================================== */
(function () {
  'use strict';
  const KN = (window.KN = window.KN || {});

  /* ---------- Perfil ------------------------------------------------------ */
  KN.profile = {
    name: 'Kevin Natera',
    role: 'Desarrollador Full-Stack',
    tagline: 'Web & Mobile · Angular · Flutter · Django',
    location: 'España',
    email: 'kevinnatera03@gmail.com',
    phone: '+34641041814',
    phoneDisplay: '+34 641 041 814',
    github: 'https://github.com/kvnnatera03',
    linkedin: 'https://www.linkedin.com/in/kevin-natera-9b241a243/',
    available: true,
    startYear: 2017,
  };

  /* ---------- Experiencias (más reciente primero) -------------------------
     `file` es el archivo del IDE que representa cada trabajo.
     NOTA: 'Brisa Apps' y 'Nodo Digital' son nombres de ejemplo: cámbialos
     por los de las empresas reales de Venezuela antes de publicar.          */
  KN.experiences = [
    {
      id: 'fandit',
      file: 'experience/03_fandit.ts',
      company: 'Fandit',
      role: 'Full-Stack Developer',
      start: '2021-03',
      end: null,
      mode: 'España',
      stack: ['Angular', 'TypeScript', 'Flutter', 'Django', 'DRF', 'Jenkins'],
      summary:
        'Aquí di el salto a full-stack: webs con Angular, apps con Flutter y APIs con Django REST.',
      points: 5,
    },
    {
      id: 'brisa',
      file: 'experience/02_brisa_apps.dart',
      company: 'Brisa Apps',
      role: 'Frontend Developer · Flutter',
      start: '2019-02',
      end: '2021-02',
      mode: 'Venezuela',
      stack: ['Flutter', 'Dart', 'BLoC', 'Provider', 'Firebase'],
      summary:
        'Dos años haciendo apps para iOS y Android con Flutter, del diseño a las tiendas. Todo frontend.',
      points: 5,
    },
    {
      id: 'nodo',
      file: 'experience/01_nodo_digital.js',
      company: 'Nodo Digital',
      role: 'Frontend Developer',
      start: '2017-09',
      end: '2019-01',
      mode: 'Venezuela',
      stack: ['HTML5', 'CSS3', 'JavaScript', 'jQuery', 'Bootstrap', 'Cordova'],
      summary:
        'Mi primer trabajo: maquetar webs, darles vida con JavaScript y mis primeras apps híbridas con Cordova.',
      points: 4,
    },
  ];

  /* ---------- Skills (se muestran como "extensiones" del IDE) ------------- */
  KN.skills = [
    { name: 'Angular', cat: 'Front-end', level: 5, color: '#b86f52', abbr: 'NG', desc: 'Mi día a día: SPAs modulares, componentes reutilizables y RxJS.' },
    { name: 'TypeScript', cat: 'Front-end', level: 5, color: '#6f8fa8', abbr: 'TS', desc: 'Si no está tipado, no me quedo tranquilo.' },
    { name: 'Flutter', cat: 'Mobile', level: 5, color: '#6fa3a0', abbr: 'FL', desc: 'Una sola base de código y iOS y Android contentos.' },
    { name: 'Dart', cat: 'Mobile', level: 5, color: '#5f8f8c', abbr: 'DT', desc: 'BLoC, Provider y capas bien separadas.' },
    { name: 'Django REST', cat: 'Back-end', level: 4, color: '#8fa37e', abbr: 'DJ', desc: 'APIs REST, serializers y autenticación.' },
    { name: 'PHP / Laravel', cat: 'Back-end', level: 4, color: '#8a86b0', abbr: 'LV', desc: 'MVC y Eloquent. Siempre a mano en la caja de herramientas.' },
    { name: 'HTML5 · CSS3', cat: 'Front-end', level: 5, color: '#c9a063', abbr: 'HC', desc: 'Maquetación semántica, responsive y accesible. Mi base.' },
    { name: 'JavaScript', cat: 'Front-end', level: 5, color: '#d2b36a', abbr: 'JS', desc: 'Donde empezó todo: ES2015+, DOM y asincronía.' },
    { name: 'Bootstrap', cat: 'Front-end', level: 4, color: '#9a86a8', abbr: 'BS', desc: 'Para levantar una UI decente en poco tiempo.' },
    { name: 'PhoneGap / Cordova', cat: 'Mobile', level: 3, color: '#7d8a8f', abbr: 'CV', desc: 'Mis primeras apps híbridas, allá por 2017.' },
    { name: 'Git', cat: 'Herramientas', level: 5, color: '#c98a6a', abbr: 'GT', desc: 'Ramas cortas, commits claros y code reviews.' },
    { name: 'Jenkins', cat: 'Herramientas', level: 3, color: '#a89a82', abbr: 'JK', desc: 'Pipelines para que desplegar no dé miedo.' },
    { name: 'Postman', cat: 'Herramientas', level: 4, color: '#c98052', abbr: 'PM', desc: 'Probar las APIs antes de que el front se queje.' },
    { name: 'Scrum · Kanban', cat: 'Metodologías', level: 5, color: '#8f9a7e', abbr: 'AG', desc: 'Sprints, dailies y retros que sirven para algo.' },
  ];

  /* ---------- Commits (panel de control de versiones = timeline) ---------- */
  KN.commits = [
    { hash: 'a3f9c21', msg: 'feat: me uno a Fandit y doy el salto a full-stack', date: '2021-03', file: 'experience/03_fandit.ts', tag: 'HEAD → main' },
    { hash: '7b2e0d4', msg: 'feat: 2 años haciendo apps con Flutter en Brisa Apps (VE)', date: '2019-02', file: 'experience/02_brisa_apps.dart' },
    { hash: '51c8a9e', msg: 'feat: primer trabajo como frontend en Nodo Digital (VE)', date: '2017-09', file: 'experience/01_nodo_digital.js' },
    { hash: '0d4f1b7', msg: 'init: Licenciatura en Informática — Universidad de Oriente', date: '2016', file: 'education.yml', tag: 'v1.0.0' },
  ];

  /* ---------- Código que la persona teclea en la escena ------------------- */
  KN.sceneCode = [
    "// kevin.ts — escribiendo el siguiente capitulo",
    "import { Developer } from '@kevin/core';",
    "",
    "const kevin = new Developer({",
    "  name: 'Kevin Natera',",
    "  role: 'Full-Stack Developer',",
    "  based: 'Spain',",
    "  since: 2017,",
    "  stack: {",
    "    web: ['Angular', 'TypeScript', 'CSS3'],",
    "    mobile: ['Flutter', 'Dart', 'Cordova'],",
    "    api: ['Django REST', 'Laravel'],",
    "  },",
    "});",
    "",
    "kevin.on('scroll', () => {",
    "  camera.zoomTo(screen);",
    "  return kevin.openPortfolio();",
    "});",
    "",
    "export default kevin;",
  ].join('\n');

  /* ---------- Archivos del IDE ------------------------------------------- */
  const BT = '`';

  KN.files = [
    {
      path: 'README.md',
      lang: 'md',
      content: [
        '# Kevin Natera',
        '',
        '> Full-Stack Developer · Web & Mobile',
        '',
        '¡Hola! Soy Kevin y llevo más de {{years}} años haciendo webs y apps.',
        'Empecé en Venezuela como frontend, maquetando y peleándome con jQuery.',
        'Luego me pasé a Flutter, y hoy trabajo como full-stack en **Fandit**,',
        'donde toco un poco de todo: **Angular**, **Flutter** y **Django**.',
        '',
        'Me gusta el código limpio, las interfaces que se sienten rápidas y',
        'los equipos que se hablan claro.',
        '',
        '## Ahora mismo',
        '',
        '- Full-Stack Developer en **Fandit** (desde marzo de 2021)',
        '- Vivo en España · castellano nativo · inglés intermedio (y mejorando)',
        '- Con ganas de nuevos proyectos',
        '',
        '## Mi stack',
        '',
        '- **Front-end:** Angular, TypeScript, JavaScript, HTML5, CSS3, Bootstrap',
        '- **Mobile:** Flutter, Dart, PhoneGap, Cordova',
        '- **Back-end:** Django REST Framework, PHP, Laravel',
        '- **Herramientas:** Git, Postman, Jenkins',
        '- **Cómo trabajo:** Scrum, Kanban, Agile',
        '',
        '## Cómo moverte por aquí',
        '',
        '1. Abre ' + BT + 'experience/' + BT + ': cada archivo es un trabajo.',
        '2. Dale a **▶ Ejecutar** y te lo resumo en la terminal.',
        '3. Abre la terminal con ' + BT + 'Ctrl + J' + BT + ' y escribe ' + BT + 'help' + BT + '.',
        '4. Con ' + BT + 'Ctrl + P' + BT + ' saltas de un archivo a otro.',
        '',
        '## Hablemos',
        '',
        '- Email: [kevinnatera03@gmail.com](mailto:kevinnatera03@gmail.com)',
        '- Teléfono: [+34 641 041 814](tel:+34641041814)',
        '- GitHub: [github.com/kvnnatera03](https://github.com/kvnnatera03)',
        '- LinkedIn: [linkedin.com/in/kevin-natera](https://www.linkedin.com/in/kevin-natera-9b241a243/)',
      ].join('\n'),
    },

    {
      path: 'experience/03_fandit.ts',
      lang: 'ts',
      exp: 'fandit',
      content: [
        '/**',
        ' * ───────────────────────────────────────────────',
        ' *  Fandit · Full-Stack Developer',
        ' *  Mar 2021 — hoy · España',
        ' * ───────────────────────────────────────────────',
        ' *  Aquí di el salto de frontend a full-stack.',
        ' */',
        "import { Component, Input } from '@angular/core';",
        "import { Experience, Stack } from '@kevin/career';",
        '',
        'const stack: Stack = {',
        "  frontend: ['Angular', 'TypeScript', 'HTML5', 'CSS3', 'Bootstrap'],",
        "  mobile:   ['Flutter', 'Dart'],",
        "  backend:  ['Django', 'Django REST Framework'],",
        "  tooling:  ['Git', 'Jenkins', 'Postman'],",
        '};',
        '',
        'export const fandit: Experience = {',
        "  company:  'Fandit',",
        "  role:     'Full-Stack Developer',",
        "  location: 'España',",
        "  start:    new Date('2021-03-01'),",
        '  end:      null,           // sigo aquí',
        '  stack,',
        '',
        '  // Lo que hago en el día a día',
        '  whatIDo: [',
        "    'Construyo aplicaciones web con Angular y TypeScript.',",
        "    'Hago apps para iOS y Android con Flutter.',",
        "    'Diseño e integro APIs REST con Django REST Framework.',",
        "    'Me encargo de que el front y el back se entiendan bien.',",
        "    'Trabajo con Scrum: planning, dailies y retros.',",
        '  ],',
        '',
        '  // Cosas en las que no negocio',
        '  principles: [',
        "    'Componentes reutilizables y tipado estricto, siempre.',",
        "    'Ramas cortas, pull requests y code review.',",
        "    'Si se puede automatizar con Jenkins, se automatiza.',",
        '  ],',
        '};',
        '',
        '@Component({',
        "  selector: 'kn-experience',",
        '  template: ' + BT + '<h2>{{ exp.role }} @ {{ exp.company }}</h2>' + BT + ',',
        '})',
        'export class ExperienceComponent {',
        '  @Input() exp: Experience = fandit;',
        '}',
      ].join('\n'),
    },

    {
      path: 'experience/02_brisa_apps.dart',
      lang: 'dart',
      exp: 'brisa',
      content: [
        '/// ───────────────────────────────────────────────',
        '///  Brisa Apps · Frontend Developer (Flutter)',
        '///  Feb 2019 — Feb 2021 · 2 años · Venezuela',
        '/// ───────────────────────────────────────────────',
        '///  Aquí me enamoré de Flutter. 100 % frontend:',
        '///  pantallas, animaciones y mucho consumo de APIs.',
        "import 'package:flutter/material.dart';",
        "import 'package:kevin/career.dart';",
        '',
        'class BrisaApps extends Experience {',
        '  const BrisaApps()',
        '      : super(',
        "          company: 'Brisa Apps',",
        "          role: 'Frontend Developer · Flutter',",
        "          location: 'Venezuela',",
        "          start: '2019-02',",
        "          end: '2021-02',",
        '        );',
        '',
        '  @override',
        '  List<String> get stack => const [',
        "        'Flutter', 'Dart', 'BLoC', 'Provider',",
        "        'Firebase', 'REST APIs', 'Material Design',",
        '      ];',
        '',
        '  @override',
        '  List<String> get highlights => const [',
        "        'Hice 5 apps para iOS y Android desde cero.',",
        "        'Pasé una app híbrida de Cordova a Flutter (y se notó).',",
        "        'Ordené la lógica con BLoC para poder testearla sin sufrir.',",
        "        'Conecté las apps con APIs REST y Firebase: login y notificaciones.',",
        "        'Las publiqué y mantuve en App Store y Google Play.',",
        '      ];',
        '}',
        '',
        '// Un widget de aquella época',
        'class ExperienceCard extends StatelessWidget {',
        '  const ExperienceCard({super.key, required this.exp});',
        '',
        '  final Experience exp;',
        '',
        '  @override',
        '  Widget build(BuildContext context) {',
        '    return Card(',
        '      child: ListTile(',
        '        title: Text(exp.role),',
        "        subtitle: Text('${exp.company} · ${exp.period}'),",
        '        trailing: const Icon(Icons.flutter_dash),',
        '      ),',
        '    );',
        '  }',
        '}',
      ].join('\n'),
    },

    {
      path: 'experience/01_nodo_digital.js',
      lang: 'js',
      exp: 'nodo',
      content: [
        '/**',
        ' * ───────────────────────────────────────────────',
        ' *  Nodo Digital · Frontend Developer',
        ' *  Sep 2017 — Ene 2019 · Venezuela',
        ' * ───────────────────────────────────────────────',
        ' *  Mi primer trabajo. Aquí aprendí que maquetar bien',
        ' *  es media batalla (y que Internet Explorer no perdona).',
        ' */',
        'const nodoDigital = {',
        "  company:  'Nodo Digital',",
        "  role:     'Frontend Developer',",
        "  location: 'Venezuela',",
        "  period:   ['2017-09', '2019-01'],",
        '',
        '  stack: [',
        "    'HTML5', 'CSS3', 'JavaScript',",
        "    'jQuery', 'Bootstrap', 'PhoneGap', 'Cordova',",
        '  ],',
        '',
        '  // Qué hacía',
        '  highlights: [',
        "    'Maquetaba webs de clientes a partir del diseño, siempre responsive.',",
        "    'Les daba vida a las interfaces con JavaScript y jQuery.',",
        "    'Hice mis primeras apps híbridas con PhoneGap/Cordova.',",
        "    'Aprendí Git, a trabajar en equipo y a no romper main.',",
        '  ],',
        '',
        "  lessonLearned: 'El mejor código es el que el siguiente dev entiende.',",
        '};',
        '',
        '$(document).ready(function () {',
        "  $('.experience').append(render(nodoDigital));",
        '});',
      ].join('\n'),
    },

    {
      path: 'skills.json',
      lang: 'json',
      content: [
        '{',
        '  "frontend": {',
        '    "Angular": 5, "TypeScript": 5, "JavaScript": 5,',
        '    "HTML5": 5, "CSS3": 5, "Bootstrap": 4',
        '  },',
        '  "mobile": {',
        '    "Flutter": 5, "Dart": 5, "PhoneGap": 3, "Cordova": 3',
        '  },',
        '  "backend": {',
        '    "Django REST Framework": 4, "PHP": 4, "Laravel": 4',
        '  },',
        '  "tools": ["Git", "Postman", "Jenkins"],',
        '  "methodologies": ["Scrum", "Kanban", "Agile"],',
        '  "languages": {',
        '    "Castellano": "Nativo",',
        '    "Inglés": "Intermedio"',
        '  },',
        '  "stillLearning": true',
        '}',
      ].join('\n'),
    },

    {
      path: 'education.yml',
      lang: 'yml',
      content: [
        '# Dónde estudié',
        'education:',
        '  - degree: Licenciatura en Informática',
        '    school: Universidad de Oriente',
        '    country: Venezuela',
        '    year: 2016',
        '',
        '# Idiomas',
        'languages:',
        '  - name: Castellano',
        '    level: nativo',
        '  - name: Inglés',
        '    level: intermedio   # le sigo dando',
        '',
        '# Cómo me gusta trabajar',
        'methodologies: [Scrum, Kanban, Agile]',
      ].join('\n'),
    },

    {
      path: 'contact.sh',
      lang: 'sh',
      content: [
        '#!/usr/bin/env bash',
        '# ¿Hablamos? Dale a ▶ Ejecutar',
        '',
        'NAME="Kevin Natera"',
        'EMAIL="kevinnatera03@gmail.com"',
        'PHONE="+34 641 041 814"',
        'GITHUB="github.com/kvnnatera03"',
        'LINKEDIN="linkedin.com/in/kevin-natera-9b241a243"',
        '',
        'echo "¡Hola! Soy $NAME."',
        'echo "Si tienes un proyecto o una vacante, escríbeme sin miedo."',
        'echo ""',
        'echo "  email     $EMAIL"',
        'echo "  teléfono  $PHONE"',
        'echo "  github    $GITHUB"',
        'echo "  linkedin  $LINKEDIN"',
        '',
        'open "mailto:$EMAIL?subject=Hola%20Kevin"',
      ].join('\n'),
    },
  ];
})();
